export const PROJECT_BACKGROUND_HYDRATION_GRACE_MS = 500
export const PROJECT_BACKGROUND_INTERACTION_COOLDOWN_MS = 500
export const PROJECT_BACKGROUND_BETWEEN_TASK_DELAY_MS = 120
export const PROJECT_BACKGROUND_POINTERMOVE_THROTTLE_MS = 160
export const PREPARATION_SPINNER_MIN_VISIBLE_MS = 140
export const DISPLAY_PAYLOAD_PREWARM_DELAY_MS = 250
export const LAYER_PAYLOAD_PREWARM_DELAY_MS = 150
export const LAYER_CACHE_WINDOW_RADIUS = 10
